const dictionaryPart7 = {
    "か": { "word": "か", "reading": "蚊", "meaning": "mosquito" },
    "かあさん": { "word": "かあさん", "reading": "母さん", "meaning": "mother" },
    "かい": { "word": "かい", "reading": "貝", "meaning": "shellfish" },
    "かいかい": { "word": "かいかい", "reading": "開会", "meaning": "opening of a meeting" },
    "かいかん": { "word": "かいかん", "reading": "会館", "meaning": "meeting hall" },
    "かいけい": { "word": "かいけい", "reading": "会計", "meaning": "account, finance" },
    "かいけつ": { "word": "かいけつ", "reading": "解決", "meaning": "settlement, solution" },
    "かいごう": { "word": "かいごう", "reading": "会合", "meaning": "meeting, assembly" },
    "がいこう": { "word": "がいこう", "reading": "外交", "meaning": "diplomacy" },
    "かいさい": { "word": "かいさい", "reading": "開催", "meaning": "holding a meeting, open an exhibition" },
    "かいさん": { "word": "かいさん", "reading": "解散", "meaning": "dissolution, breaking up" },
    "かいし": { "word": "かいし", "reading": "開始", "meaning": "start, commencement" },
    "かいしゃく": { "word": "かいしゃく", "reading": "解釈", "meaning": "explanation, interpretation" },
    "かいじょう": { "word": "かいじょう", "reading": "会場", "meaning": "assembly hall, meeting place" },
    "がいしょく": { "word": "がいしょく", "reading": "外食", "meaning": "eating out" },
    "かいすいよく": { "word": "かいすいよく", "reading": "海水浴", "meaning": "sea bathing" },
    "かいすう": { "word": "かいすう", "reading": "回数", "meaning": "number of times, frequency" },
    "かいせい": { "word": "かいせい", "reading": "快晴", "meaning": "good weather" },
    "かいせつ": { "word": "かいせつ", "reading": "解説", "meaning": "explanation, commentary" },
    "かいぜん": { "word": "かいぜん", "reading": "改善", "meaning": "betterment, improvement" },
    "かいぞう": { "word": "かいぞう", "reading": "改造", "meaning": "remodeling, reconstruction" },
    "かいつう": { "word": "かいつう", "reading": "開通", "meaning": "opening, taking effect" },
    "かいてき": { "word": "かいてき", "reading": "快適", "meaning": "pleasant, agreeable" },
    "かいてん": { "word": "かいてん", "reading": "開店", "meaning": "opening of a store" },
    "かいとう": { "word": "かいとう", "reading": "解答", "meaning": "answer, solution" },
    "かいふく": { "word": "かいふく", "reading": "回復", "meaning": "recovery, restoration" },
    "かいほう": { "word": "かいほう", "reading": "解放", "meaning": "release, liberation" },
    "かいほう": { "word": "かいほう", "reading": "開放", "meaning": "opening, open" },
    "かいよう": { "word": "かいよう", "reading": "海洋", "meaning": "ocean" },
    "がいらい": { "word": "がいらい", "reading": "外来", "meaning": "outpatient" },
    "かおり": { "word": "かおり", "reading": "香り", "meaning": "aroma, fragrance" },
    "かがく": { "word": "かがく", "reading": "科学", "meaning": "science" },
    "かがみ": { "word": "かがみ", "reading": "鏡", "meaning": "mirror" },
    "かがやく": { "word": "かがやく", "reading": "輝く", "meaning": "to shine, to glitter" },
    "かかり": { "word": "かかり", "reading": "係", "meaning": "person in charge" },
    "かかえる": { "word": "かかえる", "reading": "抱える", "meaning": "to hold in one's arms" },
    "かかく": { "word": "かかく", "reading": "価格", "meaning": "price, value" },
    "かぎる": { "word": "かぎる", "reading": "限る", "meaning": "to restrict, to limit" },
    "かぐ": { "word": "かぐ", "reading": "家具", "meaning": "furniture" },
    "がく": { "word": "がく", "reading": "額", "meaning": "forehead, frame" },
    "がくげい": { "word": "がくげい", "reading": "学芸", "meaning": "arts and sciences" },
    "がくしゃ": { "word": "がくしゃ", "reading": "学者", "meaning": "scholar" },
    "がくしゅう": { "word": "がくしゅう", "reading": "学習", "meaning": "study, learning" },
    "がくせい": { "word": "がくせい", "reading": "学生", "meaning": "student" },
    "がくねん": { "word": "がくねん", "reading": "学年", "meaning": "school year, grade" },
    "がくぶ": { "word": "がくぶ", "reading": "学部", "meaning": "department of a university" },
    "がくもん": { "word": "がくもん", "reading": "学問", "meaning": "scholarship, study" },
    "がくりょく": { "word": "がくりょく", "reading": "学力", "meaning": "academic ability" },
    "かけざん": { "word": "かけざん", "reading": "掛け算", "meaning": "multiplication" },
    "かける": { "word": "かける", "reading": "欠ける", "meaning": "to be lacking" },
    "かげ": { "word": "かげ", "reading": "影", "meaning": "shadow" },
    "かこ": { "word": "かこ", "reading": "過去", "meaning": "the past" },
    "かご": { "word": "かご", "reading": "籠", "meaning": "basket, cage" },
    "かこむ": { "word": "かこむ", "reading": "囲む", "meaning": "to surround, to encircle" },
    "かさい": { "word": "かさい", "reading": "火災", "meaning": "conflagration, fire" },
    "かし": { "word": "かし", "reading": "菓子", "meaning": "pastry" },
    "かしこい": { "word": "かしこい", "reading": "賢い", "meaning": "wise, clever" },
    "かしゅ": { "word": "かしゅ", "reading": "歌手", "meaning": "singer" },
    "かじ": { "word": "かじ", "reading": "家事", "meaning": "housework, domestic chores" },
    "かず": { "word": "かず", "reading": "数", "meaning": "number, figure" },
    "かぜい": { "word": "かぜい", "reading": "課税", "meaning": "taxation" },
    "かせぐ": { "word": "かせぐ", "reading": "稼ぐ", "meaning": "to earn income" },
    "かぞえる": { "word": "かぞえる", "reading": "数える", "meaning": "to count" },
    "かた": { "word": "かた", "reading": "型", "meaning": "model, type" },
    "かたい": { "word": "かたい", "reading": "硬い", "meaning": "hard, solid" },
    "かたかな": { "word": "かたかな", "reading": "片仮名", "meaning": "katakana" },
    "かたづける": { "word": "かたづける", "reading": "片付ける", "meaning": "to tidy up" },
    "かたまる": { "word": "かたまる", "reading": "固まる", "meaning": "to harden, to solidify" },
    "かたみち": { "word": "かたみち", "reading": "片道", "meaning": "one-way trip" },
    "かたる": { "word": "かたる", "reading": "語る", "meaning": "to talk, to tell" },
    "かち": { "word": "かち", "reading": "価値", "meaning": "value, worth" },
    "がっか": { "word": "がっか", "reading": "学科", "meaning": "study subject" },
    "がっかり": { "word": "がっかり", "reading": "がっかり", "meaning": "be disappointed" },
    "かっき": { "word": "かっき", "reading": "活気", "meaning": "energy, liveliness" },
    "がっき": { "word": "がっき", "reading": "楽器", "meaning": "musical instrument" },
    "がっきゅう": { "word": "がっきゅう", "reading": "学級", "meaning": "grade in school" },
    "かっこ": { "word": "かっこ", "reading": "格好", "meaning": "shape, appearance" },
    "かつ": { "word": "かつ", "reading": "勝つ", "meaning": "to win" },
    "かつぐ": { "word": "かつぐ", "reading": "担ぐ", "meaning": "to shoulder, to carry on shoulder" },
    "かつじ": { "word": "かつじ", "reading": "活字", "meaning": "printing type" },
    "かつどう": { "word": "かつどう", "reading": "活動", "meaning": "action, activity" },
    "かつよう": { "word": "かつよう", "reading": "活用", "meaning": "practical use, conjugation" },
    "かつりょく": { "word": "かつりょく", "reading": "活力", "meaning": "vitality, energy" },
    "かな": { "word": "かな", "reading": "仮名", "meaning": "kana" },
    "かなしい": { "word": "かなしい", "reading": "悲しい", "meaning": "sad" },
    "かなしむ": { "word": "かなしむ", "reading": "悲しむ", "meaning": "to be sad, to mourn for" },
    "かならず": { "word": "かならず", "reading": "必ず", "meaning": "certainly, without fail" },
    "かなり": { "word": "かなり", "reading": "可也", "meaning": "considerably, fairly" },
    "かね": { "word": "かね", "reading": "鐘", "meaning": "bell, chime" },
    "かねもち": { "word": "かねもち", "reading": "金持ち", "meaning": "rich man" },
    "かのう": { "word": "かのう", "reading": "可能", "meaning": "possible, practicable" },
    "かのじょ": { "word": "かのじょ", "reading": "彼女", "meaning": "she, girlfriend" },
    "かばう": { "word": "かばう", "reading": "庇う", "meaning": "to protect, to defend" },
    "かび": { "word": "かび", "reading": "黴", "meaning": "mold, mildew" },
    "かぶ": { "word": "かぶ", "reading": "株", "meaning": "stock, share" },
    "かふん": { "word": "かふん", "reading": "花粉", "meaning": "pollen" },
    "かまう": { "word": "かまう", "reading": "構う", "meaning": "to mind, to care about" },
    "がまん": { "word": "がまん", "reading": "我慢", "meaning": "patience, endurance" },
    "かみ": { "word": "かみ", "reading": "神", "meaning": "God" },
    "かみさま": { "word": "かみさま", "reading": "神様", "meaning": "God" },
    "かみのけ": { "word": "かみのけ", "reading": "髪の毛", "meaning": "hair" },
    "かみそり": { "word": "かみそり", "reading": "剃刀", "meaning": "razor" },
    "かもく": { "word": "かもく", "reading": "科目", "meaning": "school subject" },
    "かもしれない": { "word": "かもしれない", "reading": "かもしれない", "meaning": "may, might" },
    "かゆい": { "word": "かゆい", "reading": "痒い", "meaning": "itchy" },
    "から": { "word": "から", "reading": "殻", "meaning": "shell, husk" },
    "からい": { "word": "からい", "reading": "辛い", "meaning": "spicy, salty" },
    "からだ": { "word": "からだ", "reading": "体", "meaning": "body" },
    "からっぽ": { "word": "からっぽ", "reading": "空っぽ", "meaning": "empty, vacant" },
    "かりる": { "word": "かりる", "reading": "借りる", "meaning": "to borrow" },
    "かる": { "word": "かる", "reading": "刈る", "meaning": "to cut, to mow" },
    "かれ": { "word": "かれ", "reading": "彼", "meaning": "he, boyfriend" },
    "かれら": { "word": "かれら", "reading": "彼ら", "meaning": "they" },
    "かわ": { "word": "かわ", "reading": "皮", "meaning": "skin, hide" },
    "かわいそう": { "word": "かわいそう", "reading": "可哀想", "meaning": "poor, pitiable" },
    "かわかす": { "word": "かわかす", "reading": "乾かす", "meaning": "to dry" },
    "かわく": { "word": "かわく", "reading": "乾く", "meaning": "to get dry" },
    "かわり": { "word": "かわり", "reading": "代わり", "meaning": "substitute, instead" },
    "かわる": { "word": "かわる", "reading": "変わる", "meaning": "to change" },
    "かん": { "word": "かん", "reading": "缶", "meaning": "can, tin" },
    "かんかく": { "word": "かんかく", "reading": "間隔", "meaning": "space, interval" },
    "かんがえ": { "word": "かんがえ", "reading": "考え", "meaning": "thinking, idea" },
    "かんがえる": { "word": "かんがえる", "reading": "考える", "meaning": "to think" },
    "かんき": { "word": "かんき", "reading": "換気", "meaning": "ventilation" },
    "かんきょう": { "word": "かんきょう", "reading": "環境", "meaning": "environment" },
    "かんげい": { "word": "かんげい", "reading": "歓迎", "meaning": "welcome, reception" },
    "かんこう": { "word": "かんこう", "reading": "観光", "meaning": "sightseeing" },
    "かんごふ": { "word": "かんごふ", "reading": "看護婦", "meaning": "female nurse" },
    "かんさつ": { "word": "かんさつ", "reading": "観察", "meaning": "observation" },
    "かんしゃ": { "word": "かんしゃ", "reading": "感謝", "meaning": "thanks, gratitude" },
    "かんじゃ": { "word": "かんじゃ", "reading": "患者", "meaning": "a patient" },
    "かんじょう": { "word": "かんじょう", "reading": "勘定", "meaning": "calculation, bill" },
    "かんじる": { "word": "かんじる", "reading": "感じる", "meaning": "to feel" },
    "かんしん": { "word": "かんしん", "reading": "感心", "meaning": "admiration" },
    "かんする": { "word": "かんする", "reading": "関する", "meaning": "to concern, to be related" },
    "かんせい": { "word": "かんせい", "reading": "完成", "meaning": "complete, completion" },
    "かんぜん": { "word": "かんぜん", "reading": "完全", "meaning": "perfect, complete" },
    "かんそう": { "word": "かんそう", "reading": "乾燥", "meaning": "dryness, desiccation" },
    "かんたん": { "word": "かんたん", "reading": "簡単", "meaning": "simple" },
    "かんちがい": { "word": "かんちがい", "reading": "勘違い", "meaning": "misunderstanding" },
    "かんどう": { "word": "かんどう", "reading": "感動", "meaning": "being deeply moved" },
    "かんぱい": { "word": "かんぱい", "reading": "乾杯", "meaning": "cheers!" },
    "がんばる": { "word": "がんばる", "reading": "頑張る", "meaning": "to do one's best" },
    "かんり": { "word": "かんり", "reading": "管理", "meaning": "control, management" },
    "かんけい": { "word": "かんけい", "reading": "関係", "meaning": "relationship" },
    "き": { "word": "き", "reading": "気", "meaning": "spirit, mood" },
    "きあつ": { "word": "きあつ", "reading": "気圧", "meaning": "atmospheric pressure" },
    "きおく": { "word": "きおく", "reading": "記憶", "meaning": "memory" },
    "きおん": { "word": "きおん", "reading": "気温", "meaning": "temperature" },
    "きかい": { "word": "きかい", "reading": "機械", "meaning": "machine, mechanism" },
    "きかい": { "word": "きかい", "reading": "機会", "meaning": "opportunity" },
    "ぎかい": { "word": "ぎかい", "reading": "議会", "meaning": "parliament, congress" },
    "きがえる": { "word": "きがえる", "reading": "着替える", "meaning": "to change clothes" },
    "きかん": { "word": "きかん", "reading": "期間", "meaning": "period, term" },
    "きく": { "word": "きく", "reading": "効く", "meaning": "to be effective" },
    "きげん": { "word": "きげん", "reading": "機嫌", "meaning": "humor, temper" },
    "きこう": { "word": "きこう", "reading": "気候", "meaning": "climate" },
    "きざむ": { "word": "きざむ", "reading": "刻む", "meaning": "to mince, to chop" },
    "きし": { "word": "きし", "reading": "岸", "meaning": "bank, shore" },
    "きじ": { "word": "きじ", "reading": "記事", "meaning": "article, news story" },
    "ぎし": { "word": "ぎし", "reading": "技師", "meaning": "engineer, technician" },
    "きず": { "word": "きず", "reading": "傷", "meaning": "wound, injury" },
    "きたい": { "word": "きたい", "reading": "期待", "meaning": "expectation, anticipation" },
    "きたく": { "word": "きたく", "reading": "帰宅", "meaning": "returning home" },
    "きちょう": { "word": "きちょう", "reading": "貴重", "meaning": "precious, valuable" },
    "ぎちょう": { "word": "ぎちょう", "reading": "議長", "meaning": "chairman" },
    "きつい": { "word": "きつい", "reading": "きつい", "meaning": "tight, tough" },
    "きづく": { "word": "きづく", "reading": "気付く", "meaning": "to notice, to realize" },
    "きにいる": { "word": "きにいる", "reading": "気に入る", "meaning": "to be pleased with, to suit" },
    "きねん": { "word": "きねん", "reading": "記念", "meaning": "commemoration, memory" },
    "きのどく": { "word": "きのどく", "reading": "気の毒", "meaning": "pitiful, unfortunate" },
    "きふ": { "word": "きふ", "reading": "寄付", "meaning": "contribution, donation" },
    "きぼう": { "word": "きぼう", "reading": "希望", "meaning": "hope, wish" },
    "きほん": { "word": "きほん", "reading": "基本", "meaning": "basics, fundamentals" },
    "きまり": { "word": "きまり", "reading": "決まり", "meaning": "rule, settlement" },
    "きまる": { "word": "きまる", "reading": "決まる", "meaning": "to be decided" },
    "きみ": { "word": "きみ", "reading": "君", "meaning": "you" },
    "きみょう": { "word": "きみょう", "reading": "奇妙", "meaning": "strange, queer" },
    "ぎむ": { "word": "ぎむ", "reading": "義務", "meaning": "duty, obligation" },
    "きめる": { "word": "きめる", "reading": "決める", "meaning": "to decide" },
    "きもち": { "word": "きもち", "reading": "気持ち", "meaning": "feeling, mood" },
    "きゃく": { "word": "きゃく", "reading": "客", "meaning": "guest, customer" },
    "きゅう": { "word": "きゅう", "reading": "級", "meaning": "class, grade" },
    "きゅうか": { "word": "きゅうか", "reading": "休暇", "meaning": "holiday, vacation" },
    "きゅうけい": { "word": "きゅうけい", "reading": "休憩", "meaning": "rest, break" },
    "きゅうこう": { "word": "きゅうこう", "reading": "急行", "meaning": "express train" },
    "きゅうじょ": { "word": "きゅうじょ", "reading": "救助", "meaning": "relief, aid" },
    "きゅうそく": { "word": "きゅうそく", "reading": "急速", "meaning": "rapid" },
    "きゅうに": { "word": "きゅうに", "reading": "急に", "meaning": "suddenly" },
    "きゅうりょう": { "word": "きゅうりょう", "reading": "給料", "meaning": "salary, wages" },
    "きよう": { "word": "きよう", "reading": "器用", "meaning": "skillful, handy" },
    "きょうか": { "word": "きょうか", "reading": "強化", "meaning": "strengthening, reinforcement" },
    "きょうかしょ": { "word": "きょうかしょ", "reading": "教科書", "meaning": "textbook" },
    "きょうぎ": { "word": "きょうぎ", "reading": "競技", "meaning": "game, match" },
    "ぎょうぎ": { "word": "ぎょうぎ", "reading": "行儀", "meaning": "manners, behavior" },
    "きょうきゅう": { "word": "きょうきゅう", "reading": "供給", "meaning": "supply, provision" },
    "きょうさんしゅぎ": { "word": "きょうさんしゅぎ", "reading": "共産主義", "meaning": "communism" },
    "きょうし": { "word": "きょうし", "reading": "教師", "meaning": "teacher" },
    "きょうしゅく": { "word": "きょうしゅく", "reading": "恐縮", "meaning": "feeling obliged" },
    "きょうそう": { "word": "きょうそう", "reading": "競争", "meaning": "competition" },
    "きょうちょう": { "word": "きょうちょう", "reading": "強調", "meaning": "emphasis, stress" },
    "きょうつう": { "word": "きょうつう", "reading": "共通", "meaning": "common, shared" },
    "きょうどう": { "word": "きょうどう", "reading": "共同", "meaning": "cooperation, collaboration" },
    "きょうふ": { "word": "きょうふ", "reading": "恐怖", "meaning": "fear, terror" },
    "きょうみ": { "word": "きょうみ", "reading": "興味", "meaning": "interest" },
    "きょうりょく": { "word": "きょうりょく", "reading": "協力", "meaning": "cooperation" },
    "きょか": { "word": "きょか", "reading": "許可", "meaning": "permission, approval" },
    "きょく": { "word": "きょく", "reading": "局", "meaning": "bureau, department" },
    "きょり": { "word": "きょり", "reading": "距離", "meaning": "distance, range" },
    "きらい": { "word": "きらい", "reading": "嫌い", "meaning": "hate, dislike" },
    "きり": { "word": "きり", "reading": "霧", "meaning": "fog, mist" },
    "きれ": { "word": "きれ", "reading": "切れ", "meaning": "cloth, piece" },
    "きれる": { "word": "きれる", "reading": "切れる", "meaning": "to be cut, to break" },
    "きろく": { "word": "きろく", "reading": "記録", "meaning": "record, document" },
    "ぎろん": { "word": "ぎろん", "reading": "議論", "meaning": "argument, discussion" },
    "きん": { "word": "きん", "reading": "金", "meaning": "gold" },
    "ぎん": { "word": "ぎん", "reading": "銀", "meaning": "silver" },
    "きんえん": { "word": "きんえん", "reading": "禁煙", "meaning": "no smoking" },
    "きんがく": { "word": "きんがく", "reading": "金額", "meaning": "amount of money" },
    "きんこ": { "word": "きんこ", "reading": "金庫", "meaning": "safe, vault" },
    "きんし": { "word": "きんし", "reading": "禁止", "meaning": "prohibition, ban" },
    "きんせん": { "word": "きんせん", "reading": "金銭", "meaning": "money, cash" },
    "きんぞく": { "word": "きんぞく", "reading": "金属", "meaning": "metal" },
    "きんだい": { "word": "きんだい", "reading": "近代", "meaning": "modern ages" },
    "きんちょう": { "word": "きんちょう", "reading": "緊張", "meaning": "tension, nervousness" },
    "きんにく": { "word": "きんにく", "reading": "筋肉", "meaning": "muscle" },
    "きんゆう": { "word": "きんゆう", "reading": "金融", "meaning": "finance, credit" },
    "きんようび": { "word": "きんようび", "reading": "金曜日", "meaning": "Friday" }
};
