const dictionaryPart2 = {
    "外国": { "word": "外国", "reading": "がいこく", "meaning": "foreign country" },
    "外国人": { "word": "外国人", "reading": "がいこくじん", "meaning": "foreigner" },
    "会社": { "word": "会社", "reading": "かいしゃ", "meaning": "company" },
    "階段": { "word": "階段", "reading": "かいだん", "meaning": "stairs" },
    "買い物": { "word": "買い物", "reading": "かいもの", "meaning": "shopping" },
    "買う": { "word": "買う", "reading": "かう", "meaning": "to buy" },
    "返す": { "word": "返す", "reading": "かえす", "meaning": "to return something" },
    "帰る": { "word": "帰る", "reading": "かえる", "meaning": "to go home" },
    "顔": { "word": "顔", "reading": "かお", "meaning": "face" },
    "掛かる": { "word": "掛かる", "reading": "かかる", "meaning": "to take time or money" },
    "鍵": { "word": "鍵", "reading": "かぎ", "meaning": "key" },
    "書く": { "word": "書く", "reading": "かく", "meaning": "to write" },
    "学生": { "word": "学生", "reading": "がくせい", "meaning": "student" },
    "掛ける": { "word": "掛ける", "reading": "かける", "meaning": "to hang" },
    "傘": { "word": "傘", "reading": "かさ", "meaning": "umbrella" },
    "貸す": { "word": "貸す", "reading": "かす", "meaning": "to lend" },
    "風邪": { "word": "風邪", "reading": "かぜ", "meaning": "a cold" },
    "風": { "word": "風", "reading": "かぜ", "meaning": "wind" },
    "家族": { "word": "家族", "reading": "かぞく", "meaning": "family" },
    "方": { "word": "方", "reading": "かた", "meaning": "person, way of doing" },
    "学校": { "word": "学校", "reading": "がっこう", "meaning": "school" },
    "カップ": { "word": "カップ", "reading": "カップ", "meaning": "cup" },
    "家庭": { "word": "家庭", "reading": "かてい", "meaning": "household" },
    "角": { "word": "角", "reading": "かど", "meaning": "corner" },
    "鞄": { "word": "鞄", "reading": "かばん", "meaning": "bag" },
    "花瓶": { "word": "花瓶", "reading": "かびん", "meaning": "a vase" },
    "被る": { "word": "被る", "reading": "かぶる", "meaning": "to wear a hat" },
    "紙": { "word": "紙", "reading": "かみ", "meaning": "paper" },
    "カメラ": { "word": "カメラ", "reading": "カメラ", "meaning": "camera" },
    "火曜日": { "word": "火曜日", "reading": "かようび", "meaning": "Tuesday" },
    "辛い": { "word": "辛い", "reading": "からい", "meaning": "spicy" },
    "体": { "word": "体", "reading": "からだ", "meaning": "body" },
    "借りる": { "word": "借りる", "reading": "かりる", "meaning": "to borrow" },
    "軽い": { "word": "軽い", "reading": "かるい", "meaning": "light" },
    "カレンダー": { "word": "カレンダー", "reading": "カレンダー", "meaning": "calendar" },
    "川": { "word": "川", "reading": "かわ", "meaning": "river" },
    "可愛い": { "word": "可愛い", "reading": "かわいい", "meaning": "cute" },
    "漢字": { "word": "漢字", "reading": "かんじ", "meaning": "Kanji" },
    "木": { "word": "木", "reading": "き", "meaning": "tree" },
    "黄色い": { "word": "黄色い", "reading": "きいろい", "meaning": "yellow" },
    "消える": { "word": "消える", "reading": "きえる", "meaning": "to disappear" },
    "聞く": { "word": "聞く", "reading": "きく", "meaning": "to listen" },
    "北": { "word": "北", "reading": "きた", "meaning": "north" },
    "ギター": { "word": "ギター", "reading": "ギター", "meaning": "guitar" },
    "汚い": { "word": "汚い", "reading": "きたない", "meaning": "dirty" },
    "喫茶店": { "word": "喫茶店", "reading": "きっさてん", "meaning": "coffee shop" },
    "切手": { "word": "切手", "reading": "きって", "meaning": "postage stamp" },
    "切符": { "word": "切符", "reading": "きっぷ", "meaning": "ticket" },
    "昨日": { "word": "昨日", "reading": "きのう", "meaning": "yesterday" },
    "九": { "word": "九", "reading": "きゅう", "meaning": "nine" },
    "牛肉": { "word": "牛肉", "reading": "ぎゅうにく", "meaning": "beef" },
    "牛乳": { "word": "牛乳", "reading": "ぎゅうにゅう", "meaning": "milk" },
    "今日": { "word": "今日", "reading": "きょう", "meaning": "today" },
    "教室": { "word": "教室", "reading": "きょうしつ", "meaning": "classroom" },
    "兄弟": { "word": "兄弟", "reading": "きょうだい", "meaning": "siblings" },
    "去年": { "word": "去年", "reading": "きょねん", "meaning": "last year" },
    "嫌い": { "word": "嫌い", "reading": "きらい", "meaning": "to dislike" },
    "切る": { "word": "切る", "reading": "きる", "meaning": "to cut" },
    "着る": { "word": "着る", "reading": "きる", "meaning": "to wear" },
    "綺麗": { "word": "綺麗", "reading": "きれい", "meaning": "beautiful, clean" },
    "キログラム": { "word": "キログラム", "reading": "キログラム", "meaning": "kilogram" },
    "キロメートル": { "word": "キロメートル", "reading": "キロメートル", "meaning": "kilometer" },
    "銀行": { "word": "銀行", "reading": "ぎんこう", "meaning": "bank" },
    "金曜日": { "word": "金曜日", "reading": "きんようび", "meaning": "Friday" }
};
