const dictionaryPart1 = {
    "愛": { "word": "愛", "reading": "あい", "meaning": "love" },
    "挨拶": { "word": "挨拶", "reading": "あいさつ", "meaning": "greeting" },
    "青": { "word": "青", "reading": "あお", "meaning": "blue" },
    "赤": { "word": "赤", "reading": "あか", "meaning": "red" },
    "明かり": { "word": "明かり", "reading": "あかり", "meaning": "light" },
    "秋": { "word": "秋", "reading": "あき", "meaning": "autumn" },
    "開く": { "word": "開く", "reading": "あく", "meaning": "to open" },
    "上げる": { "word": "上げる", "reading": "あげる", "meaning": "to give" },
    "朝": { "word": "朝", "reading": "あさ", "meaning": "morning" },
    "足": { "word": "足", "reading": "あし", "meaning": "foot, leg" },
    "味": { "word": "味", "reading": "あじ", "meaning": "taste" },
    "明日": { "word": "明日", "reading": "あした", "meaning": "tomorrow" },
    "遊ぶ": { "word": "遊ぶ", "reading": "あそぶ", "meaning": "to play" },
    "暖かい": { "word": "暖かい", "reading": "あたたかい", "meaning": "warm" },
    "頭": { "word": "頭", "reading": "あたま", "meaning": "head" },
    "新しい": { "word": "新しい", "reading": "あたらしい", "meaning": "new" },
    "後": { "word": "後", "reading": "あと", "meaning": "after" },
    "兄": { "word": "兄", "reading": "あに", "meaning": "older brother" },
    "姉": { "word": "姉", "reading": "あね", "meaning": "older sister" },
    "あの": { "word": "あの", "reading": "あの", "meaning": "that" },
    "アパート": { "word": "アパート", "reading": "アパート", "meaning": "apartment" },
    "危ない": { "word": "危ない", "reading": "あぶない", "meaning": "dangerous" },
    "甘い": { "word": "甘い", "reading": "あまい", "meaning": "sweet" },
    "雨": { "word": "雨", "reading": "あめ", "meaning": "rain" },
    "歩く": { "word": "歩く", "reading": "あるく", "meaning": "to walk" },
    "家": { "word": "家", "reading": "いえ", "meaning": "house" },
    "言う": { "word": "言う", "reading": "いう", "meaning": "to say" },
    "池": { "word": "池", "reading": "いけ", "meaning": "pond" },
    "石": { "word": "石", "reading": "いし", "meaning": "stone" },
    "医者": { "word": "医者", "reading": "いしゃ", "meaning": "doctor" },
    "椅子": { "word": "椅子", "reading": "いす", "meaning": "chair" },
    "忙しい": { "word": "忙しい", "reading": "いそがしい", "meaning": "busy" },
    "痛い": { "word": "痛い", "reading": "いたい", "meaning": "painful" },
    "一日": { "word": "一日", "reading": "いちにち", "meaning": "one day" },
    "一番": { "word": "一番", "reading": "いちばん", "meaning": "number one" },
    "いつ": { "word": "いつ", "reading": "いつ", "meaning": "when" },
    "五日": { "word": "五日", "reading": "いつか", "meaning": "five days, the 5th day" },
    "一緒": { "word": "一緒", "reading": "いっしょ", "meaning": "together" },
    "五つ": { "word": "五つ", "reading": "いつつ", "meaning": "five" },
    "いつも": { "word": "いつも", "reading": "いつも", "meaning": "always" },
    "犬": { "word": "犬", "reading": "いぬ", "meaning": "dog" },
    "今": { "word": "今", "reading": "いま", "meaning": "now" },
    "意味": { "word": "意味", "reading": "いみ", "meaning": "meaning" },
    "妹": { "word": "妹", "reading": "いもうと", "meaning": "younger sister" },
    "入口": { "word": "入口", "reading": "いりぐち", "meaning": "entrance" },
    "居る": { "word": "居る", "reading": "いる", "meaning": "to be, to exist" },
    "要る": { "word": "要る", "reading": "いる", "meaning": "to need" },
    "入れる": { "word": "入れる", "reading": "いれる", "meaning": "to put in" },
    "色": { "word": "色", "reading": "いろ", "meaning": "color" },
    "色々": { "word": "色々", "reading": "いろいろ", "meaning": "various" },
    "上": { "word": "上", "reading": "うえ", "meaning": "up, above" },
    "後ろ": { "word": "後ろ", "reading": "うしろ", "meaning": "behind" },
    "薄い": { "word": "薄い", "reading": "うすい", "meaning": "thin" },
    "歌": { "word": "歌", "reading": "うた", "meaning": "song" },
    "歌う": { "word": "歌う", "reading": "うたう", "meaning": "to sing" },
    "生まれる": { "word": "生まれる", "reading": "うまれる", "meaning": "to be born" },
    "海": { "word": "海", "reading": "うみ", "meaning": "sea" },
    "売る": { "word": "売る", "reading": "うる", "meaning": "to sell" },
    "上着": { "word": "上着", "reading": "うわぎ", "meaning": "jacket" },
    "絵": { "word": "絵", "reading": "え", "meaning": "picture" },
    "映画": { "word": "映画", "reading": "えいが", "meaning": "movie" },
    "映画館": { "word": "映画館", "reading": "えいがかん", "meaning": "movie theater" },
    "英語": { "word": "英語", "reading": "えいご", "meaning": "English language" },
    "ええ": { "word": "ええ", "reading": "ええ", "meaning": "yes" },
    "駅": { "word": "駅", "reading": "えき", "meaning": "station" },
    "エレベーター": { "word": "エレベーター", "reading": "エレベーター", "meaning": "elevator" },
    "鉛筆": { "word": "鉛筆", "reading": "えんぴつ", "meaning": "pencil" },
    "美味しい": { "word": "美味しい", "reading": "おいしい", "meaning": "delicious" },
    "多い": { "word": "多い", "reading": "おおい", "meaning": "many" },
    "大きい": { "word": "大きい", "reading": "おおきい", "meaning": "big" },
    "大きな": { "word": "大きな", "reading": "おおきな", "meaning": "big" },
    "大勢": { "word": "大勢", "reading": "おおぜい", "meaning": "great number of people" },
    "お母さん": { "word": "お母さん", "reading": "おかあさん", "meaning": "mother" },
    "お菓子": { "word": "お菓子", "reading": "おかし", "meaning": "sweets, candy" },
    "お金": { "word": "お金", "reading": "おかね", "meaning": "money" },
    "起きる": { "word": "起きる", "reading": "おきる", "meaning": "to get up" },
    "置く": { "word": "置く", "reading": "おく", "meaning": "to put" },
    "奥さん": { "word": "奥さん", "reading": "おくさん", "meaning": "wife" },
    "お酒": { "word": "お酒", "reading": "おさけ", "meaning": "alcohol, sake" },
    "お皿": { "word": "お皿", "reading": "おさら", "meaning": "plate, dish" },
    "伯父さん": { "word": "伯父さん", "reading": "おじさん", "meaning": "uncle" },
    "教える": { "word": "教える", "reading": "おしえる", "meaning": "to teach" },
    "押す": { "word": "押す", "reading": "おす", "meaning": "to push" },
    "遅い": { "word": "遅い", "reading": "おそい", "meaning": "slow, late" },
    "お茶": { "word": "お茶", "reading": "おちゃ", "meaning": "tea" },
    "お手洗い": { "word": "お手洗い", "reading": "おてあらい", "meaning": "toilet" },
    "お父さん": { "word": "お父さん", "reading": "おとうさん", "meaning": "father" },
    "弟": { "word": "弟", "reading": "おとうと", "meaning": "younger brother" },
    "男": { "word": "男", "reading": "おとこ", "meaning": "man" },
    "男の子": { "word": "男の子", "reading": "おとこのこ", "meaning": "boy" },
    "一昨日": { "word": "一昨日", "reading": "おととい", "meaning": "the day before yesterday" },
    "一昨年": { "word": "一昨年", "reading": "おととし", "meaning": "the year before last" },
    "大人": { "word": "大人", "reading": "おとな", "meaning": "adult" },
    "お腹": { "word": "お腹", "reading": "おなか", "meaning": "stomach" },
    "同じ": { "word": "同じ", "reading": "おなじ", "meaning": "same" },
    "お兄さん": { "word": "お兄さん", "reading": "おにいさん", "meaning": "older brother" },
    "お姉さん": { "word": "お姉さん", "reading": "おねえさん", "meaning": "older sister" },
    "伯母さん": { "word": "伯母さん", "reading": "おばさん", "meaning": "aunt" },
    "お風呂": { "word": "お風呂", "reading": "おふろ", "meaning": "bath" },
    "お弁当": { "word": "お弁当", "reading": "おべんとう", "meaning": "boxed lunch" },
    "覚える": { "word": "覚える", "reading": "おぼえる", "meaning": "to remember" },
    "お巡りさん": { "word": "お巡りさん", "reading": "おまわりさん", "meaning": "policeman" },
    "重い": { "word": "重い", "reading": "おもい", "meaning": "heavy" },
    "面白い": { "word": "面白い", "reading": "おもしろい", "meaning": "interesting" },
    "泳ぐ": { "word": "泳ぐ", "reading": "およぐ", "meaning": "to swim" },
    "降りる": { "word": "降りる", "reading": "おりる", "meaning": "to get off" },
    "終わる": { "word": "終わる", "reading": "おわる", "meaning": "to finish" },
    "音楽": { "word": "音楽", "reading": "おんがく", "meaning": "music" },
    "女": { "word": "女", "reading": "おんな", "meaning": "woman" },
    "女の子": { "word": "女の子", "reading": "おんなのこ", "meaning": "girl" }
};
