const dictionaryPart2 = {
    "薬": { "word": "薬", "reading": "くすり", "meaning": "medicine" },
    "下さい": { "word": "下さい", "reading": "ください", "meaning": "please give me" },
    "果物": { "word": "果物", "reading": "くだもの", "meaning": "fruit" },
    "口": { "word": "口", "reading": "くち", "meaning": "mouth" },
    "靴": { "word": "靴", "reading": "くつ", "meaning": "shoes" },
    "靴下": { "word": "靴下", "reading": "くつした", "meaning": "socks" },
    "国": { "word": "国", "reading": "くに", "meaning": "country" },
    "曇り": { "word": "曇り", "reading": "くもり", "meaning": "cloudy" },
    "曇る": { "word": "曇る", "reading": "くもる", "meaning": "to become cloudy" },
    "暗い": { "word": "暗い", "reading": "くらい", "meaning": "dark" },
    "クラス": { "word": "クラス", "reading": "クラス", "meaning": "class" },
    "グラム": { "word": "グラム", "reading": "グラム", "meaning": "gram" },
    "来る": { "word": "来る", "reading": "くる", "meaning": "to come" },
    "車": { "word": "車", "reading": "くるま", "meaning": "car" },
    "黒": { "word": "黒", "reading": "くろ", "meaning": "black" },
    "黒い": { "word": "黒い", "reading": "くろい", "meaning": "black" },
    "警官": { "word": "警官", "reading": "けいかん", "meaning": "policeman" },
    "今朝": { "word": "今朝", "reading": "けさ", "meaning": "this morning" },
    "消す": { "word": "消す", "reading": "けす", "meaning": "to erase, to turn off power" },
    "結構": { "word": "結構", "reading": "けっこう", "meaning": "splendid, nice" },
    "結婚": { "word": "結婚", "reading": "けっこん", "meaning": "marriage" },
    "月曜日": { "word": "月曜日", "reading": "げつようび", "meaning": "Monday" },
    "玄関": { "word": "玄関", "reading": "げんかん", "meaning": "entrance" },
    "元気": { "word": "元気", "reading": "げんき", "meaning": "health, vitality" },
    "五": { "word": "五", "reading": "ご", "meaning": "five" },
    "公園": { "word": "公園", "reading": "こうえん", "meaning": "park" },
    "交差点": { "word": "交差点", "reading": "こうさてん", "meaning": "intersection" },
    "紅茶": { "word": "紅茶", "reading": "こうちゃ", "meaning": "black tea" },
    "交番": { "word": "交番", "reading": "こうばん", "meaning": "police box" },
    "声": { "word": "声", "reading": "こえ", "meaning": "voice" },
    "コート": { "word": "コート", "reading": "コート", "meaning": "coat" },
    "コーヒー": { "word": "コーヒー", "reading": "コーヒー", "meaning": "coffee" },
    "ここ": { "word": "ここ", "reading": "ここ", "meaning": "here" },
    "午後": { "word": "午後", "reading": "ごご", "meaning": "P.M., afternoon" },
    "九日": { "word": "九日", "reading": "ここのか", "meaning": "nine days, the 9th day" },
    "九つ": { "word": "九つ", "reading": "ここのつ", "meaning": "nine" },
    "午前": { "word": "午前", "reading": "ごぜん", "meaning": "A.M., morning" },
    "答える": { "word": "答える", "reading": "こたえる", "meaning": "to answer" },
    "こちら": { "word": "こちら", "reading": "こちら", "meaning": "this way" },
    "コップ": { "word": "コップ", "reading": "コップ", "meaning": "a glass" },
    "今年": { "word": "今年", "reading": "ことし", "meaning": "this year" },
    "言葉": { "word": "言葉", "reading": "ことば", "meaning": "word" },
    "子供": { "word": "子供", "reading": "こども", "meaning": "child" },
    "この": { "word": "この", "reading": "この", "meaning": "this" },
    "御飯": { "word": "御飯", "reading": "ごはん", "meaning": "rice, meal" },
    "困る": { "word": "困る", "reading": "こまる", "meaning": "to be troubled" },
    "これ": { "word": "これ", "reading": "これ", "meaning": "this" },
    "今月": { "word": "今月", "reading": "こんげつ", "meaning": "this month" },
    "今週": { "word": "今週", "reading": "こんしゅう", "meaning": "this week" },
    "こんな": { "word": "こんな", "reading": "こんな", "meaning": "such" },
    "今晩": { "word": "今晩", "reading": "こんばん", "meaning": "tonight" },
    "さあ": { "word": "さあ", "reading": "さあ", "meaning": "well..." },
    "財布": { "word": "財布", "reading": "さいふ", "meaning": "wallet" },
    "魚": { "word": "魚", "reading": "さかな", "meaning": "fish" },
    "先": { "word": "先", "reading": "さき", "meaning": "ahead" },
    "咲く": { "word": "咲く", "reading": "さく", "meaning": "to blossom" },
    "作文": { "word": "作文", "reading": "さくぶん", "meaning": "composition" },
    "差す": { "word": "差す", "reading": "さす", "meaning": "to raise an umbrella" },
    "雑誌": { "word": "雑誌", "reading": "ざっし", "meaning": "magazine" },
    "砂糖": { "word": "砂糖", "reading": "さとう", "meaning": "sugar" },
    "寒い": { "word": "寒い", "reading": "さむい", "meaning": "cold" },
    "さ来年": { "word": "さ来年", "reading": "さらいねん", "meaning": "the year after next" },
    "三": { "word": "三", "reading": "さん", "meaning": "three" },
    "散歩": { "word": "散歩", "reading": "さんぽ", "meaning": "a walk" },
    "四": { "word": "四", "reading": "し", "meaning": "four" },
    "塩": { "word": "塩", "reading": "しお", "meaning": "salt" },
    "しかし": { "word": "しかし", "reading": "しかし", "meaning": "however" },
    "時間": { "word": "時間", "reading": "じかん", "meaning": "time" },
    "仕事": { "word": "仕事", "reading": "しごと", "meaning": "work" },
    "辞書": { "word": "辞書", "reading": "じしょ", "meaning": "dictionary" },
    "静か": { "word": "静か", "reading": "しずか", "meaning": "quiet" },
    "下": { "word": "下", "reading": "した", "meaning": "down" },
    "七": { "word": "七", "reading": "しち", "meaning": "seven" },
    "質問": { "word": "質問", "reading": "しつもん", "meaning": "question" },
    "自転車": { "word": "自転車", "reading": "じてんしゃ", "meaning": "bicycle" },
    "自動車": { "word": "自動車", "reading": "じどうしゃ", "meaning": "automobile" },
    "死ぬ": { "word": "死ぬ", "reading": "しぬ", "meaning": "to die" },
    "字引": { "word": "字引", "reading": "じびき", "meaning": "dictionary" },
    "自分": { "word": "自分", "reading": "じぶん", "meaning": "oneself" },
    "閉まる": { "word": "閉まる", "reading": "しまる", "meaning": "to close" },
    "締める": { "word": "締める", "reading": "しめる", "meaning": "to fasten" },
    "閉める": { "word": "閉める", "reading": "しめる", "meaning": "to close" },
    "じゃあ": { "word": "じゃあ", "reading": "じゃあ", "meaning": "then" },
    "写真": { "word": "写真", "reading": "しゃしん", "meaning": "photograph" },
    "シャツ": { "word": "シャツ", "reading": "シャツ", "meaning": "shirt" },
    "シャワー": { "word": "シャワー", "reading": "シャワー", "meaning": "shower" },
    "十": { "word": "十", "reading": "じゅう", "meaning": "ten" },
    "授業": { "word": "授業", "reading": "じゅぎょう", "meaning": "lesson" },
    "宿題": { "word": "宿題", "reading": "しゅくだい", "meaning": "homework" },
    "上手": { "word": "上手", "reading": "じょうず", "meaning": "skillful" },
    "丈夫": { "word": "丈夫", "reading": "じょうぶ", "meaning": "strong, durable" },
    "醤油": { "word": "醤油", "reading": "しょうゆ", "meaning": "soy sauce" },
    "食堂": { "word": "食堂", "reading": "しょくどう", "meaning": "dining hall" },
    "知る": { "word": "知る", "reading": "しる", "meaning": "to know" },
    "白い": { "word": "白い", "reading": "しろい", "meaning": "white" },
    "新聞": { "word": "新聞", "reading": "しんぶん", "meaning": "newspaper" },
    "水曜日": { "word": "水曜日", "reading": "すいようび", "meaning": "Wednesday" },
    "吸う": { "word": "吸う", "reading": "すう", "meaning": "to smoke, to suck" },
    "スカート": { "word": "スカート", "reading": "スカート", "meaning": "skirt" },
    "好き": { "word": "好き", "reading": "すき", "meaning": "to like" },
    "直ぐ": { "word": "直ぐ", "reading": "すぐ", "meaning": "immediately" },
    "少し": { "word": "少し", "reading": "すこし", "meaning": "a little" },
    "涼しい": { "word": "涼しい", "reading": "すずしい", "meaning": "cool" },
    "ストーブ": { "word": "ストーブ", "reading": "ストーブ", "meaning": "heater" },
    "スプーン": { "word": "スプーン", "reading": "スプーン", "meaning": "spoon" },
    "スポーツ": { "word": "スポーツ", "reading": "スポーツ", "meaning": "sport" },
    "ズボン": { "word": "ズボン", "reading": "ズボン", "meaning": "trousers" },
    "住む": { "word": "住む", "reading": "すむ", "meaning": "to live" },
    "スリッパ": { "word": "スリッパ", "reading": "スリッパ", "meaning": "slippers" },
    "する": { "word": "する", "reading": "する", "meaning": "to do" },
    "座る": { "word": "座る", "reading": "すわる", "meaning": "to sit" },
    "背": { "word": "背", "reading": "せ", "meaning": "back, height" },
    "生徒": { "word": "生徒", "reading": "せいと", "meaning": "pupil" },
    "セーター": { "word": "セーター", "reading": "セーター", "meaning": "sweater" },
    "石鹸": { "word": "石鹸", "reading": "せっけん", "meaning": "soap" },
    "背広": { "word": "背広", "reading": "せびろ", "meaning": "business suit" },
    "狭い": { "word": "狭い", "reading": "せまい", "meaning": "narrow" },
    "ゼロ": { "word": "ゼロ", "reading": "ゼロ", "meaning": "zero" },
    "千": { "word": "千", "reading": "せん", "meaning": "thousand" },
    "先月": { "word": "先月", "reading": "せんげつ", "meaning": "last month" },
    "先週": { "word": "先週", "reading": "せんしゅう", "meaning": "last week" },
    "先生": { "word": "先生", "reading": "せんせい", "meaning": "teacher" },
    "洗濯": { "word": "洗濯", "reading": "せんたく", "meaning": "washing" },
    "全部": { "word": "全部", "reading": "ぜんぶ", "meaning": "all" },
    "掃除": { "word": "掃除", "reading": "そうじ", "meaning": "cleaning" },
    "そうして": { "word": "そうして", "reading": "そうして", "meaning": "and" },
    "そこ": { "word": "そこ", "reading": "そこ", "meaning": "there" },
    "そちら": { "word": "そちら", "reading": "そちら", "meaning": "that way" },
    "外": { "word": "外", "reading": "そと", "meaning": "outside" },
    "その": { "word": "その", "reading": "その", "meaning": "that" },
    "そば": { "word": "そば", "reading": "そば", "meaning": "near" },
    "空": { "word": "空", "reading": "そら", "meaning": "sky" },
    "それ": { "word": "それ", "reading": "それ", "meaning": "that" },
    "それから": { "word": "それから", "reading": "それから", "meaning": "after that" },
    "それでは": { "word": "それでは", "reading": "それでは", "meaning": "in that situation" }
};
